import {NumberedCodeBloc, CodeKeyWords, CodeValues, ClassName, Tab, SingleComment} from "../components/CodeTokens.jsx";
import ScrollToHash from "../components/ScrollToHash.jsx";

export default function Projects(){
    return (
        <>
            <ScrollToHash />
            <NumberedCodeBloc children={[
                <><CodeKeyWords>using</CodeKeyWords> System;</>,
                <><CodeKeyWords>using</CodeKeyWords> Projects.Backend;</>,
                <><CodeKeyWords>using</CodeKeyWords> Projects.Frontend;</>,
                <><CodeKeyWords>using</CodeKeyWords> Projects.FullStack;</>,
                <br/>,
                <><CodeKeyWords>namespace</CodeKeyWords> MarinaDotNet;</>,
                <br/>,
                <><CodeKeyWords>public static class </CodeKeyWords><ClassName>Projects</ClassName></>,
                <>&#123;</>,
                <><Tab number={2} /><CodeKeyWords>public static void</CodeKeyWords> ListAll()</>,
                <><Tab number={1} />&#123;</>,
                <><Tab number={4} /><SingleComment>Selected Projects</SingleComment></>,
                <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"---------------"</CodeValues>);</>,
                <br/>,
                <><Tab number={4} /><a href="/portfolio-react/#/projects#backend" className="primary-text">ShowBackendProjects();</a></>,
                <br/>,
                <><Tab number={4} /><a href="/portfolio-react/#/projects#frontend" className="primary-text">ShowFrontendProjects();</a></>,
                <br/>,
                <><Tab number={4} /><a href="/portfolio-react/#/projects#fullstack" className="primary-text">ShowFullStackProjects();</a></>,
                <br/>,
                <><Tab number={4} /><a href="/portfolio-react/#/projects#system" className="primary-text">ShowSystemProjects();</a></>,
                <br/>,
                <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"---------------"</CodeValues>);</>,
                <><Tab number={4} /><SingleComment>Each project reflects a step in my developer journey.</SingleComment></>,

                <section id="backend"></section>,
                <><Tab number={4} /><CodeKeyWords>private static void</CodeKeyWords> ShowBackendProjects()</>,
                <><Tab number={4} />&#123;</>,
                <><Tab number={6} /><ClassName>Project</ClassName> BookShopAPI = <CodeKeyWords>new</CodeKeyWords>()</>,
                <><Tab number={6} />&#123;</>,
                <><Tab number={8} />Name = <CodeValues>"Book Shop API"</CodeValues>,</>,
                <><Tab number={8} />Description = <CodeValues>"Is an ASP.NET Core controller-based RESTful Web API. Accessing and exchanging data from MongoDB Atlas and local SQL."</CodeValues>,</>,
                <><Tab number={8} />GitHub = <CodeKeyWords>new </CodeKeyWords><ClassName>Uri</ClassName>(<CodeValues><a href="https://github.com/MarinaDotNet/BookShop">"about: GitHub"</a></CodeValues>),</>,
                <><Tab number={8} />LifeDemo = <CodeKeyWords>new </CodeKeyWords><ClassName>Uri</ClassName>(<CodeValues><a href="/#/projects" className="in-active-link">"about: LifeDemo"</a></CodeValues>),</>,
                <><Tab number={6} />&#125;;</>,
                <br/>,
                <><Tab number={8} />BookShopAPI.Display();</>,
                <><Tab number={4} />&#125;</>,

                <section id="frontend"></section>,
                <><Tab number={4} /><CodeKeyWords>private static void</CodeKeyWords> ShowFrontendProjects()</>,
                <><Tab number={4} />&#123;</>,
                <><Tab number={6} /><ClassName>Project</ClassName> StaticPortfolio = <CodeKeyWords>new</CodeKeyWords>()</>,
                <><Tab number={6} />&#123;</>,
                <><Tab number={8} />Name = <CodeValues>"Static Portfolio website"</CodeValues>,</>,
                <><Tab number={8} />Description = <CodeValues>"A set of simple static web pages, hosted on GitHub."</CodeValues>,</>,
                <><Tab number={8} />GitHub = <CodeKeyWords>new </CodeKeyWords><ClassName>Uri</ClassName>(<CodeValues><a href="https://github.com/MarinaDotNet/marinadotnet.github.io">"about: GitHub"</a></CodeValues>),</>,
                <><Tab number={8} />LifeDemo = <CodeKeyWords>new </CodeKeyWords><ClassName>Uri</ClassName>(<CodeValues><a href="https://marinadotnet.github.io" className="in-active-link">"about: LifeDemo"</a></CodeValues>),</>,
                <><Tab number={6} />&#125;;</>,
                <br/>,
                <><Tab number={6} /><ClassName>Project</ClassName> ReactPortfolio = <CodeKeyWords>new</CodeKeyWords>()</>,
                <><Tab number={6} />&#123;</>,
                <><Tab number={8} />Name = <CodeValues>"React Vite Portfolio web application"</CodeValues>,</>,
                <><Tab number={8} />Description = <CodeValues>"A simple portfolio React-Vite application that simulates the Visual Studio, built and hosted by GitHub."</CodeValues>,</>,
                <><Tab number={8} />GitHub = <CodeKeyWords>new </CodeKeyWords><ClassName>Uri</ClassName>(<CodeValues><a href="https://github.com/MarinaDotNet/portfolio-react">"about: GitHub"</a></CodeValues>),</>,
                <><Tab number={8} />LifeDemo = <CodeKeyWords>new </CodeKeyWords><ClassName>Uri</ClassName>(<CodeValues><a href="https://marinadotnet.github.io/portfolio-react/" className="in-active-link">"about: LifeDemo"</a></CodeValues>),</>,
                <><Tab number={6} />&#125;;</>,
                <br/>,
                <br/>,
                <><Tab number={6} /><ClassName>Project</ClassName> BookShopWebApp = <CodeKeyWords>new</CodeKeyWords>()</>,
                <><Tab number={6} />&#123;</>,
                <><Tab number={8} />Name = <CodeValues>"Book Shop Web Application"</CodeValues>,</>,
                <><Tab number={8} />Description = <CodeValues>"An MVC ASP.NET Core Web Application integrated with the Book Shop API, presenting data retrieved from it."</CodeValues>,</>,
                <><Tab number={8} />GitHub = <CodeKeyWords>new </CodeKeyWords><ClassName>Uri</ClassName>(<CodeValues><a href="https://github.com/MarinaDotNet/BookShop">"about: GitHub"</a></CodeValues>),</>,
                <><Tab number={8} />LifeDemo = <CodeKeyWords>new </CodeKeyWords><ClassName>Uri</ClassName>(<CodeValues><a href="/#/projects" className="in-active-link">"about: LifeDemo"</a></CodeValues>),</>,
                <><Tab number={6} />&#125;;</>,
                <br/>,
                <><Tab number={8} />StaticPortfolio.Display();</>,
                <><Tab number={8} />ReactPortfolio.Display();</>,
                <><Tab number={8} />BookShopWebApp.Display();</>,
                <><Tab number={4} />&#125;</>,

                <section id="fullstack"></section>,
                <><Tab number={4} /><CodeKeyWords>private static void</CodeKeyWords> ShowFullStackProjects()</>,
                <><Tab number={4} />&#123;</>,
                <><Tab number={6} /><ClassName>Project</ClassName> WikiApplication = <CodeKeyWords>new</CodeKeyWords>()</>,
                <><Tab number={6} />&#123;</>,
                <><Tab number={8} />Name = <CodeValues>"Wiki Application"</CodeValues>,</>,
                <><Tab number={8} />Description = <CodeValues>"Designed to manage information about various data structures by allowing users to store, add, edit, save, and load data from a binary file."</CodeValues>,</>,
                <><Tab number={8} />GitHub = <CodeKeyWords>new </CodeKeyWords><ClassName>Uri</ClassName>(<CodeValues><a href="https://github.com/MarinaDotNet/WikiApp">"about: GitHub"</a></CodeValues>),</>,
                <><Tab number={8} />LifeDemo = <CodeKeyWords>new </CodeKeyWords><ClassName>Uri</ClassName>(<CodeValues><a href="/#/projects" className="in-active-link">"about: LifeDemo"</a></CodeValues>),</>,
                <><Tab number={6} />&#125;;</>,
                <br/>,
                <><Tab number={8} />WikiApplication.Display();</>,
                <><Tab number={4} />&#125;</>,

                <section id="system"></section>,
                <><Tab number={4} /><CodeKeyWords>private static void</CodeKeyWords> ShowSystemProjects()</>,
                <><Tab number={4} />&#123;</>,
                <><Tab number={6} /><ClassName>Project</ClassName> MultiApplicationSystem = <CodeKeyWords>new</CodeKeyWords>()</>,
                <><Tab number={6} />&#123;</>,
                <><Tab number={8} />Name = <CodeValues>"Multi-Application System"</CodeValues>,</>,
                <><Tab number={8} />Description = <CodeValues>"This system enables multiple client applications to connect to a remote server to perform astronomical calculations."</CodeValues>,</>,
                <><Tab number={8} />GitHub = <CodeKeyWords>new </CodeKeyWords><ClassName>Uri</ClassName>(<CodeValues><a href="https://github.com/MarinaDotNet/AstroRepository">"about: GitHub"</a></CodeValues>),</>,
                <><Tab number={8} />LifeDemo = <CodeKeyWords>new </CodeKeyWords><ClassName>Uri</ClassName>(<CodeValues><a href="/#/projects" className="in-active-link">"about: LifeDemo"</a></CodeValues>),</>,
                <><Tab number={6} />&#125;;</>,
                <br/>,
                <><Tab number={6} /><ClassName>Project</ClassName> DroneServiceApp = <CodeKeyWords>new</CodeKeyWords>()</>,
                <><Tab number={6} />&#123;</>,
                <><Tab number={8} />Name = <CodeValues>"Drone Service Application"</CodeValues>,</>,
                <><Tab number={8} />Description = <CodeValues>"This application is design to log and manage drones into 2 service categories: Regular and Express."</CodeValues>,</>,
                <><Tab number={8} />GitHub = <CodeKeyWords>new </CodeKeyWords><ClassName>Uri</ClassName>(<CodeValues><a href="https://github.com/MarinaDotNet/DroneServiceApplication">"about: GitHub"</a></CodeValues>),</>,
                <><Tab number={8} />LifeDemo = <CodeKeyWords>new </CodeKeyWords><ClassName>Uri</ClassName>(<CodeValues><a href="/#/projects" className="in-active-link">"about: LifeDemo"</a></CodeValues>),</>,
                <><Tab number={6} />&#125;;</>,
                <br/>,
                <><Tab number={8} />MultiApplicationSystem.Display();</>,
                <><Tab number={8} />DroneServiceApp.Display();</>,

                <><Tab number={4} />&#125;</>,
                <>&#125;</>
            ]} />
        </>
        
    );
}