import {NumberedCodeBloc, CodeKeyWords, CodeValues, ClassName, Tab, SingleComment} from "../components/CodeTokens.jsx";

export default function Skills(){
    return (
        <NumberedCodeBloc children={[
            <><CodeKeyWords>using</CodeKeyWords> Skills.LanguagesAndFrameworks;</>,
            <><CodeKeyWords>using</CodeKeyWords> Skills.Database;</>,
            <><CodeKeyWords>using</CodeKeyWords> Skills.ToolsAndTechnologies;</>,
            <><CodeKeyWords>using</CodeKeyWords> Skills.CurrentlyLearning;</>,
            <><CodeKeyWords>using</CodeKeyWords> Skills.Testing;</>,
            <br/>,
            <><CodeKeyWords>namespace</CodeKeyWords> MarinaDotNet;</>,
            <br/>,
            <><CodeKeyWords>public static class</CodeKeyWords> <ClassName>Skills</ClassName></>,
            <>&#123;</>,
            <><Tab number={2} /><CodeKeyWords>public static void</CodeKeyWords> DisplayAll()</>,
            <><Tab number={1}/>&#123;</>,
            <><Tab number={2} /><SingleComment>Developer Skill Set</SingleComment></>,
            <><Tab number={2} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"--------------------------"</CodeValues>);</>,
            <><Tab number={2} />ShowLanguagesAndFrameworks();</>,
            <><Tab number={2} />ShowDatabases();</>,
            <><Tab number={2} />ShowToolsAndTechnologies();</>,
            <><Tab number={2} />ShowCurrentlyLearning();</>,
            <><Tab number={2} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"--------------------------"</CodeValues>);</>,
            <><Tab number={2} /><SingleComment>Continually learning and evolving as a full-stack developer</SingleComment></>,
            <><Tab number={1} />&#125;</>,
            <br/>,
            <><Tab number={2}/><SingleComment>Core coding skills</SingleComment></>,
            <><Tab number={2}/><CodeKeyWords>private static void</CodeKeyWords> ShowLanguagesAndFrameworks()</>,
            <><Tab number={2} />&#123;</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- C# (.NET, ASP.NET Core")</CodeValues>);</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- JavaScript (ES6+)"</CodeValues>);</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- React"</CodeValues>);</>,
            <><Tab number={4} /><SingleComment>Was not practising for long time.</SingleComment></>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- Java"</CodeValues>);</>,
            <><Tab number={4} /><SingleComment>Very basic level.</SingleComment></>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- Python"</CodeValues>);</>,
            <><Tab number={2} />&#125;</>,
            <br/>,
            <><Tab number={2} /><SingleComment>Data knowledge</SingleComment></>,
            <><Tab number={2}/><CodeKeyWords>private static void</CodeKeyWords> ShowDatabases()</>,
            <><Tab number={2} />&#123;</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- SQL Server"</CodeValues>);</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- MongoDB"</CodeValues>);</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- Redis (Azure Cache for Redis)"</CodeValues>);</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- MariaDB"</CodeValues>);</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- SQLite"</CodeValues>);</>,
            <><Tab number={2} />&#125;</>,
            <br/>,
            <><Tab number={2} /><SingleComment>Productivity and engineering tools</SingleComment></>,
            <><Tab number={2}/><CodeKeyWords>private static void</CodeKeyWords> ShowToolsAndTechnologies()</>,
            <><Tab number={2} />&#123;</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- Git & GitHub"</CodeValues>);</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- Visual Studio & VS Code & NetBeans"</CodeValues>);</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- Entity Framework Core"</CodeValues>);</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- LINQ"</CodeValues>);</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- REST APIs"</CodeValues>);</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- Postman, Swagger"</CodeValues>);</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- Vite"</CodeValues>);</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- xUnit"</CodeValues>);</>,
            <><Tab number={2} />&#125;</>,
            <br/>,
            <><Tab number={2} /><SingleComment>What I'm exploring</SingleComment></>,
            <><Tab number={2} /><CodeKeyWords>private static void</CodeKeyWords> ShowCurrntlyLearning()</>,
            <><Tab number={2} />&#123;</>,
            <><Tab number={4} /><SingleComment>Still filling some gaps.</SingleComment></>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- React"</CodeValues>);</>,
            <><Tab number={4} /><SingleComment>Still filling some gaps.</SingleComment></>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- Vite"</CodeValues>);</>,

            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- CI/CD"</CodeValues>);</>,
            <><Tab number={4} /><ClassName>Console</ClassName>.WriteLine(<CodeValues>"- Clean Architecture & DDD in .NET")</CodeValues>;</>,
            <><Tab number={2} />&#125;</>,
            <>&#125;</>
        ]} />
    );
}